nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '/publication':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET']
            max_age: 3600
        '/publication/{id}':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'PUT', 'DELETE']
            max_age: 3600
        '/publication/new':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST']
            max_age: 3600
        '/publication/{id}/comments':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'POST']
            max_age: 3600

