services:
  krakend:
    image: devopsfaith/krakend:2.6.3
    container_name: krakend
    ports:
      - "8080:8080"
    volumes:
      - ./infra/krakend/krakend.json:/etc/krakend/krakend.json
    networks:
      - spotty-network

networks:
  spotty-network:
    name: spotty
    driver: bridge
