version: '3'

tasks:
  default:
    desc: "Show this help message"
    cmds:
      - task --list
    silent: false

  build:
    desc: "Build all Docker images"
    cmds:
      - docker-compose build
    silent: false

  rebuild:
    desc: "Rebuild all Docker images"
    cmds:
      - docker-compose build --no-cache
    silent: false

  up:
    desc: "Start all Docker containers"
    cmds:
      - docker-compose up -d
    silent: false

  down:
    desc: "Stop all Docker containers"
    cmds:
      - docker-compose down
    silent: false

  restart:
    desc: "Restart all Docker containers"
    cmds:
      - task: down
      - task: up
    silent: false

  logs:
    desc: "Follow logs of all Docker containers"
    cmds:
      - docker-compose logs -f
    silent: false

  clean:
    desc: "Remove all resources and images related to the Docker Compose project"
    cmds:
      - docker-compose down --volumes --rmi all
    silent: false

  global_clean:
    desc: "Remove all stopped containers and unused images globally"
    cmds:
      - docker system prune -af
    silent: false

  status:
    desc: "Show status of all Docker containers"
    cmds:
      - docker-compose ps
    silent: false

  service_logs:
    desc: "Follow logs of a specific service"
    vars:
      SERVICE_NAME: ""
    cmds:
      - docker-compose logs -f {{.SERVICE_NAME}}
    silent: false
