nelmio_cors:
    defaults:
        origin_regex: true
        # allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/media':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET']
            max_age: 3600
        '^/media/new':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST']
            max_age: 3600
        '^/media/delete':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ["POST", "PUT", "GET", "DELETE"]
            max_age: 3600
