version: '3.8'
services:
  event-service:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: event-service
    working_dir: /var/www/symfony
    volumes:
      - .:/var/www/symfony
    ports:
      - "8083:80"
    environment:
      APP_ENV: dev
      DB_HOST: event-database
      DB_PORT: 3306
      DATABASE_URL: mysql://symfony:symfony@event-database:3306/event-service
    entrypoint: ["/var/www/symfony/docker/entrypoint.sh"]
    depends_on:
      - event-database

  event-database:
    image: mysql:5.7
    container_name: event-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: event-service
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: