services:
  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      SERVER_IP: $SERVER_IP
      SERVER_PORT: $SERVER_PORT
      RUST_LOG: $RUST_LOG
      DATABASE_URL: $DATABASE_URL
    depends_on:
      - postgres
    networks:
      - spotty-network

  postgres:
    container_name: spotty-user-service-postgres
    image: postgres:16.3-alpine3.20
    ports:
      - "15432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spotty-network

networks:
  spotty-network:
    name: spotty
    external: true

volumes:
  postgres_data: